### ISSUE TITLE
Deployment.TestAsync does not run Transforms

### ISSUE THREAD

**Issue by darthkurak** [pulumi/pulumi-dotnet#330] opened 2024-09-02 20:03 UTC
### What happened?

Running Deployment.TestAsync does not run the new Transforms API, however it runs old Transformations. 

Running `pulumi preview` with the attached debugger shows, that Transforms API is called, so it must be something related to TestAsync implementation. 

Try example code, add a breakpoint in both methods (AutoTags and AutoTags2), debug a provided test, and see, that code executes only AutoTags, but not AutoTags2

### Example

```csharp
public class TestStack : Stack
{
    public TestStack() : base(
        new StackOptions
        {
            ResourceTransformations =
            {
                AutoTags()
            },
            ResourceTransforms =
            {
                AutoTags2()
            }
        })
    {
    }

    internal static ResourceTransform AutoTags2()
    {
        return (p, ct) =>
        {
            Console.WriteLine("Enter Transform");
            return Task.FromResult<ResourceTransformResult?>(new ResourceTransformResult(p.Args, p.Options));
        };
    }

    internal static ResourceTransformation AutoTags()
    {
        return p =>
        {
            Console.WriteLine("Enter Transformation");
            return new ResourceTransformationResult(p.Args, p.Options);
        };
    }
}

public class UnitTest1
{
    class MyMocks : IMocks
    {
        public Task<object> CallAsync(MockCallArgs args)
            => Task.FromResult<object>(args);

        public Task<(string? id, object state)> NewResourceAsync(MockResourceArgs args)
            => Task.FromResult<(string?, object)>((args.Name + "_id", args.Inputs));
    }
    
    [Fact]
    public async Task Test1()
    {
        var mocks = new MyMocks();
        var resources = await Deployment.TestAsync<TestStack>(
            mocks,
            new TestOptions
            {
                IsPreview = false,
                ProjectName = typeof(TestStack).ToString()
            });
    }
}
```

### Output of `pulumi about`

CLI          
Version      3.128.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  dotnet  unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in dotnet: executable='/usr/local/share/dotnet/dotnet' version='8.0.200'

Dependencies:
NAME    VERSION
Pulumi  3.66.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-09-02 20:57
Same issue as https://github.com/pulumi/pulumi/issues/17090.

**Comment by justinvp** [comment] 2024-09-03 02:41
Closing as a duplicate of https://github.com/pulumi/pulumi/issues/17090

**Closed by justinvp** 2024-09-03 02:41 UTC
Labels: kind/bug, resolution/duplicate
